CREATE TABLE IF NOT EXISTS `pa_book` (
  `book_id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(300) NOT NULL,
  `subtitle` varchar(300) DEFAULT '',
  `author` varchar(500) DEFAULT '',
  `isbn` varchar(100) DEFAULT '',
  `category` varchar(100) DEFAULT '',
  `publisher` varchar(300) DEFAULT '',
  `publish_year` int DEFAULT NULL,
  `publish_date` date DEFAULT NULL,
  `cover_image` varchar(500) DEFAULT '',
  `object_bucket` varchar(255) DEFAULT '',
  `object_key` varchar(500) DEFAULT '',
  `object_url` varchar(1000) DEFAULT '',
  `object_etag` varchar(255) DEFAULT '',
  `file_name` varchar(255) DEFAULT '',
  `file_size` bigint DEFAULT 0,
  `mime_type` varchar(150) DEFAULT '',
  `storage_provider` varchar(50) DEFAULT 'rustfs',
  `summary` text,
  `source_file_url` varchar(500) DEFAULT '',
  `sort` int DEFAULT 0,
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0',
  `remark` varchar(500) DEFAULT '',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`book_id`),
  KEY `idx_pa_book_title` (`title`),
  KEY `idx_pa_book_isbn` (`isbn`),
  KEY `idx_pa_book_category` (`category`),
  KEY `idx_pa_book_status` (`status`),
  KEY `idx_pa_book_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `pa_book_import_batch` (
  `import_batch_id` int NOT NULL AUTO_INCREMENT,
  `import_type` varchar(50) DEFAULT 'metadata',
  `file_name` varchar(255) DEFAULT '',
  `file_url` varchar(500) DEFAULT '',
  `total_count` int DEFAULT 0,
  `success_count` int DEFAULT 0,
  `fail_count` int DEFAULT 0,
  `status` char(1) DEFAULT '1',
  `error_message` text,
  `remark` varchar(500) DEFAULT '',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`import_batch_id`),
  KEY `idx_pa_book_import_batch_status` (`status`),
  KEY `idx_pa_book_import_batch_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `pa_book_import_detail` (
  `import_detail_id` int NOT NULL AUTO_INCREMENT,
  `import_batch_id` int NOT NULL,
  `row_no` int NOT NULL,
  `row_data` text,
  `target_id` int DEFAULT NULL,
  `status` char(1) DEFAULT '1',
  `error_message` text,
  `remark` varchar(500) DEFAULT '',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`import_detail_id`),
  KEY `idx_pa_book_import_detail_batch_id` (`import_batch_id`),
  KEY `idx_pa_book_import_detail_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
