import { get } from './request.js'

export const fetchDatabases = () => get('/api/v1/databases')
export const fetchTools = () => get('/api/v1/tools')
export const fetchTalents = () => get('/api/v1/talents')
export const fetchWordClouds = () => get('/api/v1/wordClouds')
export const fetchProjects = (params) => get('/api/v1/projects/paginate', params)
export const fetchPapers = (params) => get('/api/v1/papers/paginate', params)
export const fetchBooks = (params) => get('/api/v1/books/paginate', params)
export const fetchSoftwarePatents = (params) => get('/api/v1/softwarePatents/paginate', params)
export const fetchActivityPhotos = (params) => get('/api/v1/activityPhotos/paginate', params)
export const fetchTalentDetail = (id) => get(`/api/v1/talents/${id}`)
export const fetchSoftwarePatentStats = () => get('/api/v1/softwarePatents/stats')
export const fetchSoftwarePatentDetail = (id) => get(`/api/v1/softwarePatents/${id}`)
export const fetchPaperStats = () => get('/api/v1/papers/stats')
export const fetchPaperDetail = (id) => get(`/api/v1/papers/${id}`)
export const fetchBookStats = () => get('/api/v1/books/stats')
export const fetchBookDetail = (id) => get(`/api/v1/books/${id}`)
export const fetchProjectStats = () => get('/api/v1/projects/stats')
export const fetchProjectDetail = (id) => get(`/api/v1/projects/${id}`)
export const fetchActivities = (params) => get('/api/v1/activities/paginate', params)
export const fetchActivityDetail = (id) => get(`/api/v1/activities/${id}`)
export const fetchLandingConfig = () => get('/api/v1/site/landing')
export const fetchHomeConfig = () => get('/api/v1/site/home')
export const fetchKnowledgeGraph = () => get('/api/v1/knowledge/graph')
export const fetchActivityTimeline = () => get('/api/v1/activities/timeline')
